# generated by gen_openlane_files.py - do not edit, rerun the script
set ::env(FP_SIZING) absolute
set ::env(DIE_AREA) "0 0 3727.38 5333.92"
# PDN (see gen_openlane_files.py): met5 pitch = row period 155.04 / 3,
# offset puts one VDD/VSS pair through every channel and the top band
set ::env(FP_PDN_HORIZONTAL_HALO) 2.0
set ::env(FP_PDN_VERTICAL_HALO)   2.0
set ::env(FP_TAP_HORIZONTAL_HALO) 10.0
set ::env(FP_TAP_VERTICAL_HALO)   1.0
set ::env(FP_PDN_HWIDTH)   1.6
set ::env(FP_PDN_HSPACING) 4.0
set ::env(FP_PDN_HPITCH)   51.68
set ::env(FP_PDN_HOFFSET)  27.12
