#!/usr/bin/env python3
"""
gen_axi_files.py - floorplan files of the AXI shell measurement run
(openlane/designs/gemm_axi_shell): sizes.tcl and pin_order.cfg.

The shell alone is a pin-bound block: ~970 ports on the AXI side and ~810
on the core side, a few thousand cells at most. Its die size means nothing
(in the IP the shell sits in the margin of the core's die); what the run is
for is the cell area, flop count, timing and power of the shell itself.
So the die is just tall enough for the pins. Width 600 um (first runs: 300):
at 300 the 1613 flops of "reg" were pulled against the 971 West pins and
global routing overflowed in the first 100 um (GRT-0119), while the die as
a whole was 17 % used.

    West  (bottom -> top): S_AXI_ACLK, S_AXI_ARESETN, AXI4-Lite,
                           feature AXIS, weight AXIS, result AXIS
    East  (bottom -> top): core reset + cfg, then the core-side stream ports,
                           each bit at the same height as its AXIS bit on
                           the West edge (empty slots stand in for TSTRB), so
                           every data bit crosses the block in a straight line.

usage: gen_axi_files.py [--n 32] [--dw 8] [--height 1500] [--width 600] [--out designs]
"""
import argparse
import os
import sys


def esc(name, bit):
    return f"{name}\\[{bit}\\]"


def bus(name, width):
    return [esc(name, b) for b in range(width)]


def axil_pins():
    # AXI4-Lite, 32-bit data, 4-bit address (same widths as the KV260 IP)
    return (bus("S_AXI_AWADDR", 4) + bus("S_AXI_AWPROT", 3) + ["S_AXI_AWVALID", "S_AXI_AWREADY"] +
            bus("S_AXI_WDATA", 32) + bus("S_AXI_WSTRB", 4) + ["S_AXI_WVALID", "S_AXI_WREADY"] +
            bus("S_AXI_BRESP", 2) + ["S_AXI_BVALID", "S_AXI_BREADY"] +
            bus("S_AXI_ARADDR", 4) + bus("S_AXI_ARPROT", 3) + ["S_AXI_ARVALID", "S_AXI_ARREADY"] +
            bus("S_AXI_RDATA", 32) + bus("S_AXI_RRESP", 2) + ["S_AXI_RVALID", "S_AXI_RREADY"])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=32)
    ap.add_argument("--dw", type=int, default=8)
    ap.add_argument("--height", type=float, default=1500.0)
    ap.add_argument("--width", type=float, default=600.0)
    ap.add_argument("--out", default=os.path.join(os.path.dirname(os.path.abspath(__file__)), "designs"))
    a = ap.parse_args()
    w = a.n * a.dw
    strb = w // 8

    west = ["S_AXI_ACLK", "S_AXI_ARESETN"] + axil_pins()
    ctl = (["o_core_rst_n"] + bus("o_cfg_shift", 10) + bus("o_cfg_row_count", 9) +
           bus("o_cfg_k_block_count", 5) + bus("o_cfg_n_block_count", 5))
    if len(west) < len(ctl):
        sys.exit("gen_axi_files.py: AXI4-Lite group shorter than the cfg group")
    east = [f"${len(west) - len(ctl)}"] + ctl
    for s in ("feature", "weight"):
        west += bus(f"{s}_axis_tdata", w) + bus(f"{s}_axis_tstrb", strb) + \
            [f"{s}_axis_tvalid", f"{s}_axis_tlast", f"{s}_axis_tready"]
        east += bus(f"o_{s}_data", w) + [f"${strb}"] + [f"o_{s}_valid", f"o_{s}_last", f"i_{s}_ready"]
    west += bus("result_axis_tdata", w) + bus("result_axis_tstrb", strb) + \
        ["result_axis_tvalid", "result_axis_tlast", "result_axis_tready"]
    east += bus("i_result_data", w) + [f"${strb}"] + ["i_result_valid", "i_result_last", "o_result_ready"]

    def slots(lst):
        return sum(int(p[1:]) if p.startswith("$") else 1 for p in lst)

    nw, ne = slots(west), slots(east)
    if nw != ne:
        sys.exit(f"gen_axi_files.py: west {nw} slots, east {ne}: the edges would not line up")
    # met3 pins on the vertical edges: keep at least ~2 met3 tracks (0.68 um) per pin
    if a.height / nw < 1.36:
        sys.exit(f"gen_axi_files.py: {nw} pins on a {a.height} um edge is too dense (raise --height)")

    d = os.path.join(a.out, "gemm_axi_shell")
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(d, "pin_order.cfg"), "w") as f:
        f.write("#W\n" + "\n".join(west) + "\n#E\n" + "\n".join(east) + "\n")
    with open(os.path.join(d, "sizes.tcl"), "w") as f:
        f.write("# generated by gen_axi_files.py - do not edit, rerun the script\n")
        f.write(f"set ::env(FP_SIZING) absolute\nset ::env(DIE_AREA) \"0 0 {a.width:.2f} {a.height:.2f}\"\n")
    n_ports = len([p for p in west + east if not p.startswith("$")])
    print(f"gemm_axi_shell: die {a.width:.0f} x {a.height:.0f} um, {n_ports} ports, "
          f"{nw} slots per edge ({a.height / nw:.2f} um pitch)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
