# ---------------------------------------------------------------------------
# Level 1 - ProcessingElementRow (32 PEs) hardened as a macro.
# Size comes from sizes.tcl, pins from pin_order.cfg: both generated by
#   python3 gen_openlane_files.py --pe-area <from gemm_pe run>
# Run with a FIXED tag - gemm_array points at this run's results:
#   ./flow.tcl -design gemm_row -tag row_v1 -overwrite
# Outputs used by the parent: runs/row_v1/results/final/{lef,gds,lib}/
# ---------------------------------------------------------------------------
source $::env(DESIGN_DIR)/../gemm_common.tcl
source $::env(DESIGN_DIR)/sizes.tcl

set ::env(DESIGN_NAME)          "ProcessingElementRow"
set ::env(VERILOG_FILES)        [list $::env(DESIGN_DIR)/src/PE_row.v $::env(DESIGN_DIR)/src/PE.v]
set ::env(VERILOG_INCLUDE_DIRS) [list $::env(DESIGN_DIR)/src]
set ::env(SYNTH_DEFINES)        [list GEMM_DP_RESET=$::env(GEMM_DP_RESET)]

# a macro inside the parent: met1-met4 only, no ring, met4 straps
set ::env(DESIGN_IS_CORE)   0
set ::env(FP_PDN_CORE_RING) 0
set ::env(RT_MAX_LAYER)     "met4"

# every pin placed from the file (psum/weight column-aligned top & bottom)
set ::env(FP_PIN_ORDER_CFG) $::env(DESIGN_DIR)/pin_order.cfg

set ::env(PL_TARGET_DENSITY) 0.60

# antenna: first run had 7 pin / 6 net violations (timing, DRC, LVS clean)
set ::env(DIODE_ON_PORTS)                "in"   ;# diode on every macro input (parent wires land on our gates)
set ::env(RUN_HEURISTIC_DIODE_INSERTION) 1      ;# diodes on nets longer than HEURISTIC_ANTENNA_THRESHOLD
set ::env(GRT_ANT_ITERS)                 30
set ::env(GRT_ANT_MARGIN)                30
set ::env(HEURISTIC_ANTENNA_THRESHOLD)   50      ;# 90 left 1 violation; 50 -> 0 (row_v1, 2026-09-30)
